---
- name: Manage Apache ActiveMQ Artemis
  hosts: "{{ target_host }}"
  gather_facts: no
  become: yes   # ensure sudo
  vars:
    action: "{{ action }}" # start | stop | restart | status
    artemis_script: "/home/awx/artemis_manage.sh"

  tasks:

    - name: Debug the requested action
      debug:
        msg: "Requested action: {{ action }}"

    - name: Run Artemis management script
      ansible.builtin.raw: "{{ artemis_script }} {{ action }}"
      register: artemis_result
      ignore_errors: yes

    - name: Show script output
      debug:
        msg: "{{ artemis_result.stdout }}"
