---
- name: Manage ActiveMQ Artemis dynamically
  hosts: "{{ target_host }}"
  become: yes
  vars:
    action: "{{ action }}"  # start | stop | restart | status

  tasks:

    - name: Debug the action variable
      debug:
        msg: "Action is '{{ action }}'"

    # STOP logic (for stop or restart)
    - name: Stop Artemis safely
      when: action in ["stop", "restart"]
      ansible.builtin.systemd:
        name: artemis
        state: stopped
        force: yes
      register: stop_result
      ignore_errors: yes

    # START logic (for start or restart)
    - name: Start Artemis safely
      when: action in ["start", "restart"]
      ansible.builtin.systemd:
        name: artemis
        state: started
        force: yes

    # STATUS check
    - name: Check current status of Artemis
      ansible.builtin.systemd:
        name: artemis
      register: artemis_status

    - name: Report Artemis status
      debug:
        msg: "Artemis is currently {{ artemis_status.status.ActiveState }}"
