---
- name: Manage ActiveMQ Artemis
  hosts: "{{ target_host }}"
  become: yes
  vars:
    action: "{{ action }}"  # start | stop | restart | status

  tasks:

    - name: Debug the action variable
      debug:
        msg: "Action is '{{ action }}' (type={{ action | type_debug }})"

    # ---------------------------------------
    # STOP logic (used for stop and restart)
    - name: Stop Artemis if action is stop or restart
      when: action in ["stop", "restart"]
      ansible.builtin.systemd:
        name: artemis
        state: stopped
      register: stop_result
      ignore_errors: yes

    - name: Check if Artemis Java process is still running
      when: action in ["stop", "restart"]
      ansible.builtin.command: "pidof java"
      register: artemis_pid
      failed_when: false
      changed_when: false

    - name: Force kill Artemis if still running after stop
      when:
        - action in ["stop", "restart"]
        - artemis_pid.stdout != ""
      ansible.builtin.shell: "kill -9 {{ artemis_pid.stdout }}"
      register: force_kill
      changed_when: true

    # ---------------------------------------
    # START logic (used for start and restart)
    - name: Start Artemis if action is start or restart
      when: action in ["start", "restart"]
      ansible.builtin.systemd:
        name: artemis
        state: started
        daemon_reload: yes

    # ---------------------------------------
    # STATUS check (used for any action or standalone status)
    - name: Check the current status of Artemis
      ansible.builtin.systemd:
        name: artemis
      register: artemis_status

    - name: Report Artemis status
      debug:
        msg: "Artemis is currently {{ artemis_status.status.ActiveState }}"
