---
- name: Manage ActiveMQ Artemis dynamically
  hosts: "{{ target_host }}"
  become: yes
  vars:
    action: "{{ action }}" # can be start, stop, restart (pass via AWX extra_vars)

  tasks:
    - name: Perform the requested action on Artemis
      ansible.builtin.systemd:
        name: artemis
        state: "{{ action }}"

    - name: Check the current status of Artemis
      ansible.builtin.systemd:
        name: artemis
      register: artemis_status

    - name: Report Artemis status
      debug:
        msg: "Artemis is currently {{ artemis_status.status.ActiveState }}"
