---
- name: Manage ActiveMQ Artemis
  hosts: artemis_servers
  become: yes
  vars:
    action: "{{ action }}"   # can be start, stop, or restart

  tasks:
    - name: Start Artemis
      ansible.builtin.command: systemctl start artemis
      when: action == "start"

    - name: Stop Artemis
      ansible.builtin.command: systemctl stop artemis
      when: action == "stop"

    - name: Restart Artemis
      ansible.builtin.command: systemctl restart artemis
      when: action == "restart"

    - name: Check Status
      ansible.builtin.command: systemctl status artemis
      when: action == "status"
