---
- name: Manage ActiveMQ Artemis via AWX
  hosts: "{{ target_host }}"
  gather_facts: no
  become: yes          # Use sudo
  vars:
    action: "{{ action }}"   # start | stop | restart | status
    systemctl_path: "/u01/artemis/mastermq/bin"

  tasks:

    - name: Debug the action
      debug:
        msg: "Action requested: {{ action }}"

    # STOP logic
    - name: Stop Artemis if needed
      when: action in ["stop", "restart"]
      ansible.builtin.systemd:
        name: artemis
        state: stopped
        force: yes
        executable: "{{ systemctl_path }}"
      register: stop_result
      ignore_errors: yes

    # START logic
    - name: Start Artemis if needed
      when: action in ["start", "restart"]
      ansible.builtin.systemd:
        name: artemis
        state: started
        force: yes
        executable: "{{ systemctl_path }}"

    # STATUS logic
    - name: Check Artemis status
      ansible.builtin.systemd:
        name: artemis
        executable: "{{ systemctl_path }}"
      register: artemis_status

    - name: Report Artemis status
      debug:
        msg: "Artemis is currently {{ artemis_status.status.ActiveState }}"
