---
- name: Manage ActiveMQ Artemis
  hosts: "{{ target_host }}"
  become: yes
  vars:
    action: "{{ action }}"  # start | stop | restart | status

  tasks:

    - name: Debug the action variable
      debug:
        msg: "Action is '{{ action }}' (type={{ action | type_debug }})"

    # ---------------------------------------
    # STOP logic (used for stop and restart)
    - name: Stop Artemis if action is stop or restart
      when: action in ["stop", "restart"]
      ansible.builtin.systemd:
        name: artemis
        state: stopped
        force: yes
      register: stop_result
      ignore_errors: yes

    # ---------------------------------------
    # START logic (used for start and restart)
    - name: Start Artemis if action is start or restart
      when: action in ["start", "restart"]
      ansible.builtin.systemd:
        name: artemis
        state: started
        force: yes

    # ---------------------------------------
    # STATUS check (used for any action or standalone status)
    - name: Check the current status of Artemis
      ansible.builtin.systemd:
        name: artemis
      register: artemis_status

    - name: Report Artemis status
      debug:
        msg: "Artemis is currently {{ artemis_status.status.ActiveState }}"
