---
- name: Manage JBoss Domain
  hosts: "{{ target_host }}"
  gather_facts: false
  vars:
    jboss_home: "/u01/T24/JBOSS"
    domain_config: "{{ domain_config | default('domain-cbo.xml') }}"
    host_config: "{{ host_config | default('host-master-cbo-dev.xml') }}"
    action: "{{ action }}"
    server_group: "{{ server_group | default('') }}"
    jboss_user: "{{ jboss_user }}"
    jboss_pass: "{{ jboss_pass }}"

  tasks:

    - name: Stop server group
      shell: "{{ jboss_home }}/bin/jboss-cli.sh --user={{ jboss_user }} --password={{ jboss_pass }} --connect --command='/server-group={{ server_group }}:stop-servers()'"
      when: action == "stop_profile"

    - name: Start server group
      shell: "{{ jboss_home }}/bin/jboss-cli.sh --user={{ jboss_user }} --password={{ jboss_pass }} --connect --command='/server-group={{ server_group }}:start-servers()'"
      when: action == "start_profile"

    - name: Stop entire domain via kill
      shell: "ps -ef | grep jboss | awk '{print $2}' | xargs kill -9"
      when: action == "stop_domain"

    - name: Start entire domain via script
      shell: "nohup {{ jboss_home }}/bin/domain.sh --domain-config={{ domain_config }} --host-config={{ host_config }} &"
      args:
        chdir: "{{ jboss_home }}/bin"
      async: 0
      poll: 0
      when: action == "start_domain"
