---
- name: Manage JBoss Profiles
  hosts: "{{ target_host }}"
  gather_facts: false
  vars:
    jboss_home: "/u01/T24/JBOSS"
    jboss_user: "{{ jboss_user }}"
    jboss_pass: "{{ jboss_pass }}"
    server_group: "{{ server_group | default('') }}"
    action: "{{ action }}" # start_profile / stop_profile
    jboss_cli: "{{ jboss_home }}/bin/jboss-cli.sh --user={{ jboss_user }} --password={{ jboss_pass }} --connect"

  tasks:

    # -----------------------------
    # Start/Stop a server group
    # -----------------------------
    - name: Start servers in server group
      shell: "{{ jboss_cli }} --command='/server-group={{ server_group }}:start-servers()'"
      when: action == "start_profile"

    - name: Stop servers in server group
      shell: "{{ jboss_cli }} --command='/server-group={{ server_group }}:stop-servers()'"
      when: action == "stop_profile"




