---
- name: Manage JBoss Domain (stop/start)
  hosts: "{{ target_host }}"
  gather_facts: false
  vars:
    jboss_home: "/u01/T24/JBOSS"
    action: "{{ action }}" # stop_domain / start_domain

  tasks:

    # -----------------------------
    # Stop the entire domain safely
    # -----------------------------
    - name: Stop entire JBoss domain
      raw: |
        PIDS=$(ps -ef | grep jboss | grep -v grep | awk '{print $2}')
        if [ -n "$PIDS" ]; then
          echo "$PIDS" | xargs kill -9
        else
          echo "No JBoss domain process found"
        fi
      ignore_errors: yes
      when: action == "stop_domain"

    # -----------------------------
    # Start the entire domain
    # -----------------------------
    - name: Start entire domain
      shell: "{{ jboss_home }}/start-domain.sh"
      args:
        chdir: "{{ jboss_home }}"
      async: 0
      poll: 0
      when: action == "start_domain"
