---
- name: Manage JBoss Domain
  hosts: "{{ target_host }}"      # dynamic host
  gather_facts: false
  vars:
    jboss_user: "{{ jboss_user }}"
    jboss_pass: "{{ jboss_pass }}"
    server_group: "{{ server_group | default('') }}"
    action: "{{ action }}"        # start_profile, stop_profile, start_domain, stop_domain
    domain_config: "{{ domain_config | default('domain.xml') }}"
    host_config: "{{ host_config | default('host.xml') }}"
    jboss_cli: "{{ jboss_home }}/bin/jboss-cli.sh --user={{ jboss_user }} --password={{ jboss_pass }} --connect"
    jboss_home: "/u01/T24/JBOSS"

  tasks:

    # -----------------------------
    # Start/Stop a server group
    # -----------------------------
    - name: Start servers in server group
      command: "{{ jboss_cli }} --command='/server-group={{ server_group }}:start-servers()'"
      when: action == "start_profile"

    - name: Stop servers in server group
      command: "{{ jboss_cli }} --command='/server-group={{ server_group }}:stop-servers()'"
      when: action == "stop_profile"

    # -----------------------------
    # Stop the whole domain
    # -----------------------------
    - name: Stop entire domain
      command: "{{ jboss_cli }} --command=':shutdown'"
      when: action == "stop_domain"

    # -----------------------------
    # Start the whole domain
    # -----------------------------
    - name: Start entire domain
      shell: "nohup {{ jboss_home }}/bin/domain.sh --domain-config={{ domain_config }} --host-config={{ host_config }} &"
      args:
        chdir: "{{ jboss_home }}/bin"
      async: 0
      poll: 0
      when: action == "start_domain"
