---
- name: Manage JBoss server group
  hosts: 10.1.237.222
  gather_facts: false
  vars:
    jboss_user: "{{ jboss_user }}"       # dynamic username
    jboss_pass: "{{ jboss_pass }}"       # dynamic password
    jboss_cli: "/u01/T24/JBOSS/bin/jboss-cli.sh --user={{ jboss_user }} --password={{ jboss_pass }} --connect"
    server_group: "{{ server_group }}"   # dynamic server group

  tasks:
    - name: Start servers in server group
      command: "{{ jboss_cli }} --command='/server-group={{ server_group }}:start-servers()'"
      tags: start_profile

    - name: Stop servers in server group
      command: "{{ jboss_cli }} --command='/server-group={{ server_group }}:stop-servers()'"
      tags: stop_profile
