---
- name: Manage JBoss Domain (stop/start)
  hosts: "{{ target_host }}"
  gather_facts: false
  vars:
    jboss_home: "/u01/T24/JBOSS"
    action: "{{ action }}" # stop_domain / start_domain
    domain_config: "{{ domain_config }}"
    host_config: "{{ host_config }}"
    ansible_shell_executable: /bin/sh
    ansible_python_interpreter: /bin/false

  tasks:

    # -----------------------------
    # Stop the entire domain safely
    # -----------------------------
    - name: Stop entire JBoss domain
      raw: |
        PIDS=$(ps -ef | grep jboss | grep -v grep | awk '{print $2}')
        if [ -n "$PIDS" ]; then
          echo "$PIDS" | xargs kill -9
        else
          echo "No JBoss domain process found"
        fi
      ignore_errors: yes
      when: action == "stop_domain"

    # -----------------------------
    # Start the entire domain
    # -----------------------------
    - name: Start entire domain
      raw: |
        cd {{ jboss_home }}/bin
        nohup {{ jboss_home }}/bin/domain.sh --domain-config={{ domain_config }} --host-config={{ host_config }} > /dev/null 2>&1 &
      when: action == "start_domain"
