---
- name: Test SSH connectivity on JBoss servers
  hosts: "{{ target_host }}"
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: "{{ ssh_private_key }}"
    ansible_user: "{{ ssh_user }}"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Test SSH connection using raw command
      raw: whoami
      register: ssh_test

    - name: Show SSH test result
      debug:
        msg: "SSH works! Connected as: {{ ssh_test.stdout }}"
